### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "testpass123"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=user@example.com


### Delete a user with a given ID
DELETE http://localhost:3000/auth/2


### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "new_email@example.com"
}
